## Linear Regression, Ridge And Lasso 

In [1]:
## House Pricing dataset 

import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('train.csv')

In [3]:
data.head()

ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0   1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1   2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2   4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3   5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4   7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   

   ptratio   black  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     18.7  394.63   2.94  33.4  
3     18.7  396.90   5.33  36.2  
4     15.2  395.60  12.43  22.9

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
data.head()

ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0   1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1   2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2   4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3   5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4   7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   

   ptratio   black  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     18.7  394.63   2.94  33.4  
3     18.7  396.90   5.33  36.2  
4     15.2  395.60  12.43  22.9

In [6]:
## dividing the dataset into indemendent and dependent features
test_data=pd.read_csv('test.csv')
x=data.iloc[:,:-1]  ## independent features 

y=data.iloc[:,-1] ## Dependent features

In [7]:
test_data.head()
x_test=test_data.iloc[:,:-1]
y_test=test_data.iloc[:,-1]

In [8]:
x_test.head()

ID     crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0   3  0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242   
1   6  0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222   
2   8  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
3   9  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
4  10  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   

   ptratio   black  
0     17.8  392.83  
1     18.7  394.12  
2     15.2  396.90  
3     15.2  386.63  
4     15.2  386.71

In [9]:
y_test.head()

0     4.03
1     5.21
2    19.15
3    29.93
4    17.10
Name: lstat, dtype: float64

In [10]:
x.head()


ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0   1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1   2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2   4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3   5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4   7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   

   ptratio   black  lstat  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     18.7  394.63   2.94  
3     18.7  396.90   5.33  
4     15.2  395.60  12.43

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [12]:
lin_reg=LinearRegression()

In [13]:
mse=cross_val_score(lin_reg,x,y,scoring='neg_mean_squared_error',cv=5)


In [14]:
print(mse)

[ -16.72433342  -27.48311816  -33.30084617 -105.78761097  -68.73463254]


In [15]:
mean_mse=np.mean(mse)
print(mean_mse)

-50.406108255096214


In [16]:
# lin_reg.predict()

In [17]:
### Ridge Regression 

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [18]:
ridge=Ridge()

params={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,20]}

ridge_regressor=GridSearchCV(ridge,params,scoring='neg_mean_squared_error',cv=5)

ridge_regressor.fit(x,y)


GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 20]},
             scoring='neg_mean_squared_error')

In [19]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 20}
-43.744098091795465


In [20]:
## Lasso Regression 
from sklearn.linear_model import Lasso
lasso=Lasso()

In [21]:
params={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,45,50,55,100]}

lasso_regressor=GridSearchCV(lasso,params,scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(x,y)

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.191e+03, tolerance: 2.609e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.494e+03, tolerance: 2.225e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.591e+03,

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 30, 35, 40, 45, 50, 55, 100]},
             scoring='neg_mean_squared_error')

In [22]:
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)



{'alpha': 1}
-49.047750636978535


In [23]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [34]:
## Linear Regression

lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)
mse=cross_val_score(lin_reg,x_train,y_train,scoring='neg_mean_squared_error',cv=5)

mean_mse=np.mean(mse)
print(mean_mse)

-30.45867482687341


In [26]:
## Ridge Regression with x_train and y_train 

ridge_regressor.fit(x_train,y_train)
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 1}
-30.002614278937756


In [27]:
## Lasso Regression with x_train and y_train 
lasso_regressor.fit(x_train,y_train)
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.001e+03, tolerance: 1.612e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.014e+03, tolerance: 1.464e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.783e+03,

{'alpha': 0.01}
-30.40878780196177


In [32]:
# Score of the Lasso regression 

y_pred=lasso_regressor.predict(x_test)

from sklearn.metrics import r2_score

r2_score1=r2_score(y_pred,y_test)
print(r2_score1)

0.6603815200192271


In [33]:
# Score of the Ridge Regression 

y_pred=ridge_regressor.predict(x_test)

r2_score1=r2_score(y_pred,y_test)
print(r2_score1)

0.6573190490623255


In [36]:
# Score of the Linear Regression 

y_pred=lin_reg.predict(x_test)

r2_score1=r2_score(y_pred,y_test)
print(r2_score1)

0.6616617282402695


In [37]:

### Logistic Regression 


In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
from sklearn.datasets import load_breast_cancer

In [41]:
df=load_breast_cancer()
## Incependent features 
x=pd.DataFrame(df['data'],columns=df['feature_names'])


In [42]:
x.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [43]:
## Dependent feature
y=pd.DataFrame(df['target'],columns=['target'])

In [44]:
y.head()

target
0       0
1       0
2       0
3       0
4       0

In [47]:
y['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [48]:
# train test split test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)


In [51]:
params=[{'C':[1,5,10]},{'max_iter':[100,150]}]


In [77]:
model=LogisticRegression(C=100,max_iter=100)

In [78]:
model=GridSearchCV(model1,param_grid=params,scoring='f1',cv=5)
model.fit(x_train,y_train)

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1

GridSearchCV(cv=5, estimator=LogisticRegression(C=100),
             param_grid=[{'C': [1, 5, 10]}, {'max_iter': [100, 150]}],
             scoring='f1')

In [79]:
model.best_params_

{'max_iter': 150}

In [80]:

model.best_score_

np.float64(0.9598077001616112)

In [81]:
y_pred=model.predict(x_test)

In [82]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1])

In [83]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [84]:
confusion_matrix(y_test,y_pred)

array([[ 64,   3],
       [  3, 118]])

In [85]:
accuracy_score(y_test,y_pred)

0.9680851063829787

In [86]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        67
           1       0.98      0.98      0.98       121

    accuracy                           0.97       188
   macro avg       0.97      0.97      0.97       188
weighted avg       0.97      0.97      0.97       188

