## Label Encoding

Label encoding and oridinal encoding are two techniques used to encode categorical data as numerical data

Laebel encoding involves assinging a unique numerical label to each category in the variable. The labels are usually assinged in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible value (red,green,blue), we can represent it using label encoding as follows. 

1. Red : 1
2. Green : 2
3. blue : 3

In [2]:
import pandas as pd
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [4]:
df.head()

,color
0,red
1,blue
2,green
3,green
4,red


In [5]:
from sklearn.preprocessing import LabelEncoder 
lbl_encoder=LabelEncoder()

In [6]:
lbl_encoder.fit_transform(df[['color']])

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [7]:
lbl_encoder.transform([['red']])

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [10]:
lbl_encoder.transform([['green']])

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [12]:
lbl_encoder.transform([['blue']])

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

### Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assinged a numerical value based on its position in the order. For example, if we have a categorical variable " education level " with four possible value (high school , collage , graduate, post-graduate) we can represent it using ordinal encoding as follows:

1. High school : 1
2. Collage : 2
3. Graduate : 3
4. Post-Graduate : 4

In [14]:
## ordinal Encoding
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [15]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [16]:
df


,size
0,small
1,medium
2,large
3,medium
4,small
5,large


In [21]:
## create instance of ordinal encoder and then fit_transform

encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [22]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [23]:
encoder.transform([['small']])

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

## Target Guided Ordinal Encoding
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical varaible with large number of unique  categories, and we want to use this variable as a feature in our machine learning model. 

In Target Guided ORdinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for the category. This creates a monotonic relationship between the categorical variable and the target variable which can improve the predictive power of our model 

In [24]:
# create a sample dataframe with a categorical variable and a target variable 

df=pd.DataFrame({

    'city':['New york','London','Paris','Tokyo','New york','Paris'],
    'price':[200,150,300,250,180,320]
})

In [25]:
df

,city,price
0,New york,200
1,London,150
2,Paris,300
3,Tokyo,250
4,New york,180
5,Paris,320


In [28]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [29]:
mean_price

{'London': 150.0, 'New york': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [30]:
df['city_encoded']=df['city'].map(mean_price)

In [33]:
df[['price','city_encoded']]

,price,city_encoded
0,200,190.0
1,150,150.0
2,300,310.0
3,250,250.0
4,180,190.0
5,320,310.0


In [34]:
## Assingment based on the time to total_bill
import seaborn as sns
data=sns.load_dataset('tips')

In [35]:
data.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [38]:
filter_data=data[['time','total_bill']]

In [39]:
filter_data.head()

,time,total_bill
0,Dinner,16.99
1,Dinner,10.34
2,Dinner,21.01
3,Dinner,23.68
4,Dinner,24.59


In [41]:
mean_bill=filter_data.groupby('time')['total_bill'].mean().to_dict()

C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_12336\3590096216.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill=filter_data.groupby('time')['total_bill'].mean().to_dict()


In [42]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [44]:
filter_data['encoded_total_bill']=filter_data['time'].map(mean_bill)

C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_12336\2551989162.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_data['encoded_total_bill']=filter_data['time'].map(mean_bill)


In [46]:
filter_data.head()

,time,total_bill,encoded_total_bill
0,Dinner,16.99,20.797159
1,Dinner,10.34,20.797159
2,Dinner,21.01,20.797159
3,Dinner,23.68,20.797159
4,Dinner,24.59,20.797159
