## Numpy 

Numpy is a funcamental library for scientfic computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy. focuing on arrays and vectorized operations.

In [1]:
# Install the numpy library :- pip install numpy 
import numpy as np

In [2]:
## Create array using numpy 
# create a 1D array 

arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [3]:
arr2=np.array([1,2,3,4,5])
arr2.reshape((1,5)) # 1 row and 5 coloums


array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5],[5,6,7,8,6]])
print(arr2)
arr2.shape


[[1 2 3 4 5]
 [5 6 7 8 6]]


(2, 5)

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## Identity matrix 

np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
## Attrubute of numpy Array 

arr=np.array([[1,2,3],[4,5,6]])

print("Array : \n",arr)
print("shape : ", arr.shape)
print("Number of dimensions : ", arr.ndim)
print("Size (number of elements) :",arr.size)
print("Data type : " , arr.dtype)
print("Item size (in bytes) : ",arr.itemsize)

Array : 
 [[1 2 3]
 [4 5 6]]
shape :  (2, 3)
Number of dimensions :  2
Size (number of elements) : 6
Data type :  int64
Item size (in bytes) :  8


In [21]:
## Numpy vectorized Operation 

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise addition 
print("Addition : ", arr1+arr2)

## Element wise subtraction 
print("Subtraction : ", arr1-arr2)

## Element wise multiplication 
print("Multiplication : ", arr1+arr2)

## Element wise divid
print("Division : " , arr1/arr2)

Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [11 22 33 44 55]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [23]:
## Universal Function 

arr=np.array([1,2,3,4,5,6])

# square root
print(np.sqrt(arr))

# exponential 
print(np.exp(arr))

# sine 
print(np.sin(arr))

# natural log 
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
## arrayslicing and Indexing 

arr=np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
print('Array :\n',arr)

Array :
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [33]:
arr[0][0]

np.int64(1)

In [34]:
arr[1:,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [36]:
print(arr[0:2,1:])

[[2 3 4 5]
 [6 7 8 9]]


In [37]:
## modify array elements 
arr[0][0]=100
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [38]:
arr[1:]=100
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [39]:
## Statistical concepts -Normalization
# To have a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

# calculate the mean and standard deviation 
mean=np.mean(data)
std_dev=np.std(data)

# Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized Data : ",normalized_data)

Normalized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [41]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean=np.mean(data)
print("Mean : ", mean)

# Median 
median=np.median(data)
print('Mdeian ', median)

# Standard Deviation 
std_dev=np.std(data)
print('Standard Deviation : ', std_dev)

#Variance 
variance=np.var(data)
print("variance :",variance)


Mean :  5.5
Mdeian  5.5
Standard Deviation :  2.8722813232690143
variance : 8.25


In [43]:
## Logical Operation 

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

array([ 6,  7,  8,  9, 10])

In [44]:
data > 8

array([False, False, False, False, False, False, False, False,  True,
        True])

In [45]:
data <4

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [47]:
data[(data>=3) & (data<=7)]

array([3, 4, 5, 6, 7])